services:
  rabbitmq1:
    image: rabbitmq
    container_name: rabbitmq1
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}]
    ports:
      - 5672:5672
      - 15672:15672
    hostname: rmq01
    command: apt -y install iputils-ping
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie:ro
    networks:
      - rabbitmq
  
  rabbitmq2:
    image: rabbitmq
    container_name: rabbitmq2
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}]
    ports:
      - 5673:5672
    hostname: rmq02
    command: apt -y install iputils-ping
    volumes:
      - ./rabbitmq2:/var/lib/rabbitmq
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie:ro
    networks:
      - rabbitmq

networks:
  rabbitmq:
    driver: bridge